#define PDstandardNth1(u,i,j,k) (p1o2dx*(-(u)[CCTK_GFINDEX3D(cctkGH,-1 + i,j,k)] + (u)[CCTK_GFINDEX3D(cctkGH,1 + i,j,k)]))
#define PDstandardNth2(u,i,j,k) (p1o2dy*(-(u)[CCTK_GFINDEX3D(cctkGH,i,-1 + j,k)] + (u)[CCTK_GFINDEX3D(cctkGH,i,1 + j,k)]))
#define PDstandardNth3(u,i,j,k) (p1o2dz*(-(u)[CCTK_GFINDEX3D(cctkGH,i,j,-1 + k)] + (u)[CCTK_GFINDEX3D(cctkGH,i,j,1 + k)]))
#define PDstandardNth11(u,i,j,k) (p1odx2*((u)[CCTK_GFINDEX3D(cctkGH,-1 + i,j,k)] + (u)[CCTK_GFINDEX3D(cctkGH,1 + i,j,k)] - 2*(u)[CCTK_GFINDEX3D(cctkGH,i,j,k)]))
#define PDstandardNth22(u,i,j,k) (p1ody2*((u)[CCTK_GFINDEX3D(cctkGH,i,-1 + j,k)] + (u)[CCTK_GFINDEX3D(cctkGH,i,1 + j,k)] - 2*(u)[CCTK_GFINDEX3D(cctkGH,i,j,k)]))
#define PDstandardNth33(u,i,j,k) (p1odz2*((u)[CCTK_GFINDEX3D(cctkGH,i,j,-1 + k)] + (u)[CCTK_GFINDEX3D(cctkGH,i,j,1 + k)] - 2*(u)[CCTK_GFINDEX3D(cctkGH,i,j,k)]))
#define PDstandardNth12(u,i,j,k) (p1o4dxdy*((u)[CCTK_GFINDEX3D(cctkGH,-1 + i,-1 + j,k)] - (u)[CCTK_GFINDEX3D(cctkGH,-1 + i,1 + j,k)] - (u)[CCTK_GFINDEX3D(cctkGH,1 + i,-1 + j,k)] + (u)[CCTK_GFINDEX3D(cctkGH,1 + i,1 + j,k)]))
#define PDstandardNth13(u,i,j,k) (p1o4dxdz*((u)[CCTK_GFINDEX3D(cctkGH,-1 + i,j,-1 + k)] - (u)[CCTK_GFINDEX3D(cctkGH,-1 + i,j,1 + k)] - (u)[CCTK_GFINDEX3D(cctkGH,1 + i,j,-1 + k)] + (u)[CCTK_GFINDEX3D(cctkGH,1 + i,j,1 + k)]))
#define PDstandardNth21(u,i,j,k) (p1o4dxdy*((u)[CCTK_GFINDEX3D(cctkGH,-1 + i,-1 + j,k)] - (u)[CCTK_GFINDEX3D(cctkGH,-1 + i,1 + j,k)] - (u)[CCTK_GFINDEX3D(cctkGH,1 + i,-1 + j,k)] + (u)[CCTK_GFINDEX3D(cctkGH,1 + i,1 + j,k)]))
#define PDstandardNth23(u,i,j,k) (p1o4dydz*((u)[CCTK_GFINDEX3D(cctkGH,i,-1 + j,-1 + k)] - (u)[CCTK_GFINDEX3D(cctkGH,i,-1 + j,1 + k)] - (u)[CCTK_GFINDEX3D(cctkGH,i,1 + j,-1 + k)] + (u)[CCTK_GFINDEX3D(cctkGH,i,1 + j,1 + k)]))
#define PDstandardNth31(u,i,j,k) (p1o4dxdz*((u)[CCTK_GFINDEX3D(cctkGH,-1 + i,j,-1 + k)] - (u)[CCTK_GFINDEX3D(cctkGH,-1 + i,j,1 + k)] - (u)[CCTK_GFINDEX3D(cctkGH,1 + i,j,-1 + k)] + (u)[CCTK_GFINDEX3D(cctkGH,1 + i,j,1 + k)]))
#define PDstandardNth32(u,i,j,k) (p1o4dydz*((u)[CCTK_GFINDEX3D(cctkGH,i,-1 + j,-1 + k)] - (u)[CCTK_GFINDEX3D(cctkGH,i,-1 + j,1 + k)] - (u)[CCTK_GFINDEX3D(cctkGH,i,1 + j,-1 + k)] + (u)[CCTK_GFINDEX3D(cctkGH,i,1 + j,1 + k)]))
